version: '3.9'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.5-enterprise
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/123456
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
